/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerInvestidor;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Investidor;

/**
 *
 * @author moijo
 */
public class JInvestidor extends javax.swing.JFrame {

    public JInvestidor(Investidor investidor) {
        initComponents();
        this.investidor = investidor;
        controller = new ControllerInvestidor(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btConsSaldo = new javax.swing.JButton();
        btConsExtrato = new javax.swing.JButton();
        btDepositar = new javax.swing.JButton();
        btSacar = new javax.swing.JButton();
        btComprarMoeda = new javax.swing.JButton();
        btVenderMoeda = new javax.swing.JButton();
        btAtualizarCot = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Bem vindo, nome!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Escolha uma Opção:");

        btConsSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConsSaldo.setText("Consultar saldo");
        btConsSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btConsSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsSaldoActionPerformed(evt);
            }
        });

        btConsExtrato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConsExtrato.setText("Consultar extrato");
        btConsExtrato.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btConsExtrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsExtratoActionPerformed(evt);
            }
        });

        btDepositar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDepositar.setText("Depositar");
        btDepositar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositarActionPerformed(evt);
            }
        });

        btSacar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSacar.setText("Sacar");
        btSacar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSacarActionPerformed(evt);
            }
        });

        btComprarMoeda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btComprarMoeda.setText("Comprar criptomoedas");
        btComprarMoeda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btComprarMoeda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btComprarMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarMoedaActionPerformed(evt);
            }
        });

        btVenderMoeda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVenderMoeda.setText("Vender criptomoedas");
        btVenderMoeda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVenderMoeda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVenderMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderMoedaActionPerformed(evt);
            }
        });

        btAtualizarCot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAtualizarCot.setText("Atualizar Cotação");
        btAtualizarCot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAtualizarCot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarCotActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btConsSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btConsExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAtualizarCot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btComprarMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btVenderMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(68, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btComprarMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVenderMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtualizarCot, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void btComprarMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarMoedaActionPerformed
        new JComprarMoeda(investidor).setVisible(true);
    }//GEN-LAST:event_btComprarMoedaActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btConsSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsSaldoActionPerformed
        new JSaldo(investidor).setVisible(true);
    }//GEN-LAST:event_btConsSaldoActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btConsExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsExtratoActionPerformed
        new JExtratos(investidor).setVisible(true);
    }//GEN-LAST:event_btConsExtratoActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositarActionPerformed
        new JDeposito(investidor).setVisible(true);
    }//GEN-LAST:event_btDepositarActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSacarActionPerformed
        new JSaque(investidor).setVisible(true);
    }//GEN-LAST:event_btSacarActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btVenderMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderMoedaActionPerformed
        new JVenderMoeda(investidor).setVisible(true);
    }//GEN-LAST:event_btVenderMoedaActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btAtualizarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarCotActionPerformed
        controller.atualizaValorCotas(investidor);
    }//GEN-LAST:event_btAtualizarCotActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        controller.Sair();
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * 
     * @return 
     */
    public JLabel getLblNome() {
        return lblNome;
    }
    /**
     * 
     * @param lblNome 
     */
    public void setLblNome(JLabel lblNome) {
        this.lblNome = lblNome;
    } 

    /**
     * 
     * @return 
     */
    public Investidor getInvestidor() {
        return investidor;
    }
    /**
     *
     * @param investidor
     */
    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }
    
    
 
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JUsuario().setVisible(true);
//            }
//        });
//    }
    ControllerInvestidor controller;
    Investidor investidor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarCot;
    private javax.swing.JButton btComprarMoeda;
    private javax.swing.JButton btConsExtrato;
    private javax.swing.JButton btConsSaldo;
    private javax.swing.JButton btDepositar;
    private javax.swing.JButton btSacar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVenderMoeda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
